[desktop]
followUpQueueMode = "steer"
preventSleepWhileRunning = true
show-context-window-usage = true
appearanceTheme = "dark"
codeFontSize = 14

[desktop.appearanceDarkChromeTheme.fonts]
code = '"Hack Nerd Font", "D2CodingLigature Nerd Font"'
